// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4240.Robot.subsystems;

import org.usfirst.frc4240.Robot.OI;
import org.usfirst.frc4240.Robot.Robot;
import org.usfirst.frc4240.Robot.RobotMap;
import org.usfirst.frc4240.Robot.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Ultrasonic;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.ADXRS450_Gyro;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import com.ctre.*;
import com.kauailabs.navx.frc.AHRS;


/**
 *
 */
public class DriveTrain extends Subsystem {
	
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon rightFrontMotor = RobotMap.driveTrainRightFrontMotor;
    private final CANTalon rightRearMotor = RobotMap.driveTrainRightRearMotor;
    private final CANTalon leftFrontMotor = RobotMap.driveTrainLeftFrontMotor;
    private final CANTalon leftRearMotor = RobotMap.driveTrainLeftRearMotor;
    private final RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;
    private final Encoder quadratureEncoder1 = RobotMap.driveTrainQuadratureEncoder1;
    private final Ultrasonic ultrasonic2 = RobotMap.driveTrainUltrasonic2;
    private final Ultrasonic ultrasonic1 = RobotMap.driveTrainUltrasonic1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new DriveWithJoyStick());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        
        
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
}
    
    	public void takeJoystickInputs(double left, double right) {
    
        		   		 
    		 
	    	robotDrive.arcadeDrive(org.usfirst.frc4240.Robot.Robot.oi.logitech);
			//robotDrive.tankDrive(Robot.oi.logitech.getRawAxis(1), Robot.oi.logitech.getRawAxis(5));
			//robotDrive.arcadeDrive(Robot.oi.logitech.getRawAxis(1), Robot.oi.logitech.getRawAxis(5));
	}
	
	
	public void stop() {
		robotDrive.arcadeDrive(0, 0);
	}

}

